ALTER DEFAULT PRIVILEGES IN SCHEMA batch
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO funds_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA batch
GRANT USAGE, SELECT ON SEQUENCES TO funds_app;

ALTER DEFAULT PRIVILEGES FOR ROLE funds_admin IN SCHEMA batch
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO funds_app;

ALTER DEFAULT PRIVILEGES FOR ROLE funds_admin IN SCHEMA batch
GRANT USAGE, SELECT ON SEQUENCES TO funds_app;