GRANT USAGE ON SCHEMA batch TO funds_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA batch
TO funds_app;

GRANT SELECT
ON ALL TABLES IN SCHEMA batch
TO funds_app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA batch
TO funds_app;