ALTER DEFAULT PRIVILEGES IN SCHEMA analytics
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO funds_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA analytics
GRANT USAGE, SELECT ON SEQUENCES TO funds_app;

ALTER DEFAULT PRIVILEGES FOR ROLE funds_admin IN SCHEMA analytics
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO funds_app;

ALTER DEFAULT PRIVILEGES FOR ROLE funds_admin IN SCHEMA analytics
GRANT USAGE, SELECT ON SEQUENCES TO funds_app;

GRANT USAGE ON SCHEMA analytics TO funds_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA analytics
TO funds_app;

GRANT SELECT
ON ALL TABLES IN SCHEMA analytics
TO funds_app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA analytics
TO funds_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA sec_financials
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO funds_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA sec_financials
GRANT USAGE, SELECT ON SEQUENCES TO funds_app;

ALTER DEFAULT PRIVILEGES FOR ROLE funds_admin IN SCHEMA sec_financials
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO funds_app;

ALTER DEFAULT PRIVILEGES FOR ROLE funds_admin IN SCHEMA sec_financials
GRANT USAGE, SELECT ON SEQUENCES TO funds_app;

GRANT USAGE ON SCHEMA sec_financials TO funds_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA sec_financials
TO funds_app;

GRANT SELECT
ON ALL TABLES IN SCHEMA sec_financials
TO funds_app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA sec_financials
TO funds_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO funds_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO funds_app;

ALTER DEFAULT PRIVILEGES FOR ROLE funds_admin IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO funds_app;

ALTER DEFAULT PRIVILEGES FOR ROLE funds_admin IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO funds_app;

GRANT USAGE ON SCHEMA public TO funds_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO funds_app;

GRANT SELECT
ON ALL TABLES IN SCHEMA public
TO funds_app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO funds_app;